### ISSUE TITLE
Copyright glitch?

### ISSUE THREAD

**Issue by mro** [tangzhentao/ConstraintPack#1]
Hi tangzhentao,

could you please give a comment regarding http://ericasadun.com/2016/11/10/cocoapods-and-copyright-claims/ ?

I think you may know Erica Sadun, right?

**Comment by codetalks-new** [comment]
用了别人代码应该在 README 上说清楚.

**Comment by tangzhentao** [comment]
@mro Yes, of course I know Erica Sadun. I have given a comment. Thank you!

**Comment by tangzhentao** [comment]
@banxi1988 谢谢提醒。其实我已经说明了代码的出处。
<img width="984" alt="copyright" src="https://cloud.githubusercontent.com/assets/14369028/20243731/014e69d4-a99f-11e6-9d68-a7256f7da4a0.png">

但我收到了邮件，里面的意思是“不要提到书和作者的名字”。我现在已经把书和作者名字删除了。不知道还有没有问题。

**Comment by wwwjfy** [comment]
邮件的意思是说你不能声明 copyright 是属于你的，而不是不要提作者的名字。
![screen shot 2016-11-14 at 19 12 49](https://cloud.githubusercontent.com/assets/126527/20262725/5a52b940-aa9e-11e6-8450-d8e76f67fa57.png)
![screen shot 2016-11-14 at 19 13 22](https://cloud.githubusercontent.com/assets/126527/20262741/6fedae2c-aa9e-11e6-9739-1c95ed903f1f.png)

**Comment by wwwjfy** [comment]
并且，如果你不是作者，不要修改 license （原来是 BSD，这个 repo 里声明是 MIT）

**Comment by tangzhentao** [comment]
@wwwjfy 明白了，谢谢！
